### ISSUE TITLE
there is no /config.yaml in /config!

### ISSUE THREAD

**Issue by LeoStrange26** [matfrei/CLIPMasterPrints#1]
there is no /config.yaml in /config!

**Comment by matfrei** [comment]
config.yaml was intended as a generic placeholder for any config file. I clarified this in the README.

**Comment by LeoStrange26** [comment]
maybe an example？you know it's hard for beginers. thx

**Comment by matfrei** [comment]
Just pick any config you like from the dir and run it, e.g.

```python train/mine.py --config-path config/cmp_artworks.yaml```

to mine an example that does the same as the one in our teaser figure.
